/**
 * External imports
 */
import { Map } from 'immutable';

/**
 * Folder model interface, based on an immutable map
 */
export interface Folder extends Map<string, any> {

	/**
	 * Folder ID (string generated by database)
	 */
	id: string;

	/**
	 * Folder name
	 */
	name: string;

	/**
	 * ID of the folder this folder is in (string generated by database)
	 */
	path?: string;

	/**
	 * Folder position (start position is always 1)
	 */
	position: number;

	/**
	 * Flag for root folder
	 */
	isRoot: boolean;

}
