/**
 * File: Folder model
 */

import { Map } from 'immutable';

/**
 * Folder model interface, based on an immutable map
 */
export interface Folder extends Map<string, any> {

	/**
	 * Folder ID (string generated by database)
	 */
	id: string;

	/**
	 * Folder name
	 */
	name: string;

	/**
	 * Time when this folder was created (YYYY-MM-DD)
	 */
	created: string;

	/**
	 * Time when this folder was last updated (YYYY-MM-DD)
	 */
	updated?: string;

	/**
	 * ID of the folder this folder is in (string generated by database)
	 */
	path?: string;

	/**
	 * Folder position (start position is always 1)
	 */
	position: number;

	/**
	 * Flag for root folder
	 */
	isRoot: boolean;

}
