/**
 * File: Label model
 */

import { Map } from 'immutable';

/**
 * Label model interface, based on an immutable map
 */
export interface Label extends Map<string, any> {

	/**
	 * Label ID (string generated by database)
	 */
	id: string;

	/**
	 * Label name
	 */
	name: string;

	/**
	 * Label color (HEX)
	 */
	color: string;

}
